language: python
python:
  - 3.8
deploy:
  matrix:
  - provider: pypi
    on:
      branch: master
      tags: true
    distributions: sdist bdist_wheel
    python: 3.8
    user: edx
  password:
    secure: t1MbCgsliHg6txDq/Mq5S9pTby7QxI80Hi4QVlhK8zdqRocDSAzuCkzbSeuRgdXVS9nBlsVJvaut+/aTsc8PkMm1z7Hx3yoYVV3STK4gzNQc0suJL3Aefu0gvw7P8ojwEvIghhTu79MyA1TIaj8NxnhSFsm8zgIcyqvKK4Sul/hzPZrUFE8A1fuSMa71Jxq+jukmWxmNsvcs73DY2no+nkuPJxppn3fXUaMovGL6sT6BOk6cda2ez7aUU3T+t49aQMJ5J6dHPRBqEKk4if2gqtkZMHi01dWPbKUlUowCck5RdxP3B+ssoyQze6lqtgujaoigQd9NpvHAui2eLLcrLFcA9rgh9hp22O+Ro62VdRFN2LqeZGXCGxBDJ8aB2menvYQ0oSpAw27EFrVti9bCDDV+Q0yBWLCTXTXC6wMtTa8K9lfpW/Y1fOfo4zr/am2ScA2uX0lJ/inAiH498yJXISGJ7yA4NvayAOvEo2KTvl536oYDsFoxVNJnZlu7WMCnDdaN7IC65G4gcDDoFcUheKjllelqHcVNWJq/P63pHPMo3nZIDWF01+E4ksAqmtzZf1EQSi+HD0lIALt+h0jiiS3tVwdGR5PVEZ8xjsLPo14iSk2/qOF3ib9UxhP+z8ktpkwEAl9APFCAhqWmAHBb/YrYnkVvnAKpSunLVLNEOTs=
script: travis_terminate 0
